import os
import json
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def launch_3d_simulation_mesh(run_directory_path):
    """
    Accepts a dynamic run folder path passed from the main pipeline executor,
    extracts the binary numerical metrics, and renders the interactive 3D terrain canvas.
    """
    npy_path = os.path.join(run_directory_path, "heightmap.npy")
    folder_name = os.path.basename(run_directory_path)
    
    print(f"\n🎮 [RECONSTRUCTION] Waking up 3D engine workspace layer...")
    print(f"📡 Parsing matrix array parameters directly from: {npy_path}")
    
    if not os.path.exists(npy_path):
        print(f"❌ Reconstruction Error: Missing matrix targets inside '{run_directory_path}'")
        return

    # 1. Load the binary array data matrices generated by your teammate
    height_grid = np.load(npy_path)
    rows, cols = height_grid.shape
    print(f"📐 Resolution Dimensions Synchronized: {cols} columns x {rows} rows")
    
    # 2. Structure coordinate vector grids matching dynamic aspect constraints
    x_indices = np.arange(0, cols)
    y_indices = np.arange(0, rows)
    X, Y = np.meshgrid(x_indices, y_indices)
    
    x_flat = X.flatten()
    y_flat = Y.flatten()
    z_flat = height_grid.flatten()
    
    # 3. Configure dark theme WebGL style frame graphics 
    fig = plt.figure(figsize=(11, 8.5), facecolor='#111116')
    ax = fig.add_subplot(111, projection='3d', facecolor='#111116')
    
    ax.xaxis.set_pane_color((0.1, 0.1, 0.12, 1.0))
    ax.yaxis.set_pane_color((0.1, 0.1, 0.12, 1.0))
    ax.zaxis.set_pane_color((0.1, 0.1, 0.12, 1.0))
    
    print("📈 Pulling calculated elevations into the 3D surface mesh layout grid...")
    surf = ax.plot_trisurf(
        x_flat, y_flat, z_flat, 
        cmap='jet', 
        linewidth=0.01, 
        antialiased=True,
        vmin=0, vmax=21
    )
    
    cbar = fig.colorbar(surf, ax=ax, shrink=0.5, aspect=6, pad=0.08)
    cbar.set_label('Metric Depth Elevation Scale (Meters)', color='#ffffff', fontsize=11, labelpad=10)
    cbar.ax.yaxis.set_tick_params(color='#ffffff', labelcolor='#ffffff')
    
    ax.set_title(f"SIH 2026 - Reconstruction Dashboard [{folder_name}]", color='#ffffff', fontsize=12, pad=15, fontweight='bold')
    ax.set_xlabel("X (Width Matrix)", color='#aaaaaa', fontsize=9)
    ax.set_ylabel("Y (Height Matrix)", color='#aaaaaa', fontsize=9)
    ax.set_zlabel("Z Elevation (m)", color='#aaaaaa', fontsize=9)
    
    ax.tick_params(colors='#ffffff', labelsize=8)
    
    print("🚀 Launching unified 3D reconstruction viewport module...")
    plt.show()